version: '3'
services:
  app1:
    image: backtesting-ui-website:1.0
    ports:
      - "3001:3000"
    restart: always
  app2:
    image: backtesting-ui-website:1.0
    ports:
      - "3002:3000"
    restart: always
  app3:
    image: backtesting-ui-website:1.0
    ports:
      - "3003:3000"
    restart: always
  nginx:
    image: nginx:1.26.2
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
